site_name: CPGEOM
site_description: Documentation personnelle – SIG, Qualité des données, Juridique et Projets
site_author: Abdoulhakim Elmi

theme : 
  name : readthedocs

nav:
    - Accueil: index.md
    - Métadonnées: meta.md
    - Etude des cas : edc.md
    - Administration BDD : admi.md
    - cas pratique Adm BDD : pra.md
    - Exo correction : exorole.md
    - IDG : IDG.md