site_name: CPGEOM
site_description: Documentation personnelle – SIG
site_author: Abdoulhakim Elmi
site_url: ""
repo_url: https://github.com/Geohorn33/idgeo
repo_name: GitHub

copyright: "© 2026 Abdoulhakim Elmi"

theme : 
  name : readthedocs

nav:
    - Accueil: index.md
    - Métadonnées: meta.md
    - Etude des cas : edc.md
    - Administration BDD : admi.md
    - cas pratique Adm BDD : pra.md